apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/part-of: kube-prometheus
  name: certmanager
  namespace: monitoring-satellite
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - certmanager
  selector:
    matchLabels:
      app.kubernetes.io/component: certmanager
      app.kubernetes.io/name: certmanager
      app.kubernetes.io/part-of: kube-prometheus
