apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: certmanager
    app.kubernetes.io/name: certmanager
    app.kubernetes.io/part-of: kube-prometheus
  name: certmanager-metrics
  namespace: certmanager
spec:
  ports:
  - name: metrics
    port: 9402
  selector:
    app: cert-manager
    app.kubernetes.io/component: controller
