apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
  name: otel-collector
  namespace: monitoring-satellite
