apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
  name: otel-collector
  namespace: monitoring-satellite
spec:
  ports:
  - name: jaeger
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
  type: ClusterIP
