apiVersion: v1
data:
  collector.yaml: |
    receivers:
      jaeger:
        protocols:
          thrift_http:
            endpoint: "0.0.0.0:14268"
      otlp:
        protocols:
          grpc: # on port 4317
          http: # on port 4318
    exporters:
      otlp:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-team": "a756ca0b4e06b484d337d6201c224a4f"
          "x-honeycomb-dataset": "gitpod-production"

    extensions:
      health_check:
      pprof:
      zpages:
    service:
      telemetry:
        logs:
          level: "debug"
      extensions: [health_check, pprof,  zpages]
      pipelines:
        traces:
          receivers: [jaeger, otlp]
          processors: [ ]
          exporters: ["otlp"]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
  name: otel-collector
  namespace: monitoring-satellite
