apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
  name: otel-collector
  namespace: monitoring-satellite
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: kube-prometheus
    spec:
      containers:
      - args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector:0.38.0
        name: otelcol
        volumeMounts:
        - mountPath: /conf
          name: otel-collector
      nodeSelector:
        gitpod.io/workload_services: "true"
      serviceAccountName: otel-collector
      volumes:
      - configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: otel-collector
        name: otel-collector
