apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.24.0
  name: alertmanager-main
  namespace: monitoring-satellite
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: Black_Hole
      group_by: ['...']
      routes:
      - receiver: IDECriticalReceiver
        match:
          severity: critical
          team: ide
      - receiver: webappCriticalReceiver
        match:
          severity: critical
          team: webapp
      - receiver: workspaceCriticalReceiver
        match:
          severity: critical
          team: workspace
      - receiver: platformCriticalReceiver
        match:
          severity: critical
          team: platform
      - receiver: globalCriticalReceiver
        match:
          severity: critical
      - receiver: SlackWarning
        match:
          severity: warning
      - receiver: SlackInfo
        match:
          severity: info
      - receiver: Watchdog
        match:
          alertname: Watchdog
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 6h
    inhibit_rules:
    - source_match:
        severity: critical
      target_match_re:
        severity: warning|info
      equal:
      - alertname
    - source_match:
        severity: warning
      target_match_re:
        severity: info
      equal:
      - alertname
    receivers:
    - name: Black_Hole
    - name: Watchdog
    - name: IDECriticalReceiver
      pagerduty_configs:
      - send_resolved: true
        routing_key: '0919ef23ba224603d019b99a0d296b34'

    - name: webappCriticalReceiver
      pagerduty_configs:
      - send_resolved: true
        routing_key: '0919ef23ba224603d019b99a0d296b34'

    - name: workspaceCriticalReceiver
      pagerduty_configs:
      - send_resolved: true
        routing_key: '0919ef23ba224603d019b99a0d296b34'

    - name: platformCriticalReceiver
      pagerduty_configs:
      - send_resolved: true
        routing_key: '0919ef23ba224603d019b99a0d296b34'

    - name: globalCriticalReceiver
      pagerduty_configs:
      - send_resolved: true
        routing_key: '0919ef23ba224603d019b99a0d296b34'

    - name: SlackWarning
      slack_configs:
      - send_resolved: true
        api_url: https://hooks.slack.com/services/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
        channel: '#a_gitpod-io_warning'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}{{ end }}] prod-meta-us02 Monitoring'
        text: |
          {{ range .Alerts }}
          **Please take a look when possible**
          *Cluster:* {{ .Labels.cluster }}
          *Alert:* {{ .Labels.alertname }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        actions:
        - type: button
          text: 'Runbook :book:'
          url: '{{ .CommonAnnotations.runbook_url }}'
    - name: SlackInfo
      slack_configs:
      - send_resolved: true
        api_url: https://hooks.slack.com/services/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
        channel: '#a_gitpod-io_info'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}{{ end }}] prod-meta-us02 Monitoring'
        text: |
          {{ range .Alerts }}
          **No need for human intervention :slightly_smiling_face:
          *Cluster:* {{ .Labels.cluster }}
          *Alert:* {{ .Labels.alertname }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        actions:
        - type: button
          text: 'Runbook :book:'
          url: '{{ .CommonAnnotations.runbook_url }}'
    templates: []
type: Opaque
