apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: gitpod
    app.kubernetes.io/part-of: kube-prometheus
  name: gitpod-ws-proxy
  namespace: monitoring-satellite
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: keep
      regex: gitpod_(.*)
      sourceLabels:
      - __name__
    port: metrics
  jobLabel: app.kubernetes.io/component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/component: ws-proxy
      app.kubernetes.io/name: gitpod
      app.kubernetes.io/part-of: kube-prometheus
